version: "3.9"
services:
  mysqldb:
    image: mysql:8
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: organizationdb
    ports:
      - "3306:3306"
    networks:
      - organization-mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  user:
    build: ./user-service
    ports:
      - "8081:8081"
    networks:
      - organization-mysql
      - site-user
      - organization-user
    depends_on:
       mysqldb:
         condition: service_healthy

  site:
    build: ./site-service
    ports:
      - "8082:8082"
    networks:
      - organization-mysql
      - site-user
      - organization-site
    depends_on:
      - mysqldb
      - user

  organization:
    build: ./organization-service
    ports:
      - "8083:8083"
    networks:
      - organization-mysql
      - organization-user
      - organization-site
    depends_on:
      - mysqldb
      - user
      - site

networks:
  organization-mysql:
  site-user:
  organization-user:
  organization-site:
